#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CustomRowView.Resource", IsApplication=true)]

namespace CustomRowView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FlowerBuds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Fruits = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Legumes = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Tubers = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Vegetables = 2130837511;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Image = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int List = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int Text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Text1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Text2 = 2131034114;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeScreen = 2130903041;
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
