#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CustomRowView.Resource", IsApplication=true)]

namespace CustomRowView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_call = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_chat = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_mail = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bulbs = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CustomSelector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dafault_avatar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FlowerBuds = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Fruits = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Legumes = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Tubers = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Vegetables = 2130837515;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int Image = 2131034119;
			
			// aapt resource value: 0x7f050031
			public const int List = 2131034161;
			
			// aapt resource value: 0x7f050000
			public const int Text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Text1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Text2 = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int avatar = 2131034122;
			
			// aapt resource value: 0x7f050021
			public const int emergency_separator = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int emergency_title = 2131034146;
			
			// aapt resource value: 0x7f050008
			public const int employee_name = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int employee_title = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int homephone_call = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int homephone_chat = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int homephone_layout = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int homephone_val = 2131034130;
			
			// aapt resource value: 0x7f050019
			public const int mail_separator = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int mail_title = 2131034138;
			
			// aapt resource value: 0x7f05000f
			public const int mobiphone_call = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int mobiphone_chat = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int mobiphone_layout = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int mobiphone_val = 2131034126;
			
			// aapt resource value: 0x7f05001e
			public const int othermail_layout = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int othermail_send = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int othermail_val = 2131034143;
			
			// aapt resource value: 0x7f05000c
			public const int phone_title = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int quick_call = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int quick_contact_layout = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int quick_mail = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int quick_sms = 2131034117;
			
			// aapt resource value: 0x7f050023
			public const int rela_name = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int relahomephone_call = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int relahomephone_chat = 2131034156;
			
			// aapt resource value: 0x7f050029
			public const int relahomephone_layout = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int relahomephone_val = 2131034154;
			
			// aapt resource value: 0x7f050027
			public const int relamobiphone_call = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int relamobiphone_chat = 2131034152;
			
			// aapt resource value: 0x7f050025
			public const int relamobiphone_layout = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int relamobiphone_val = 2131034150;
			
			// aapt resource value: 0x7f050024
			public const int relationship = 2131034148;
			
			// aapt resource value: 0x7f05002f
			public const int relaworkphone_call = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int relaworkphone_chat = 2131034160;
			
			// aapt resource value: 0x7f05002d
			public const int relaworkphone_layout = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int relaworkphone_val = 2131034158;
			
			// aapt resource value: 0x7f05000b
			public const int separator = 2131034123;
			
			// aapt resource value: 0x7f05001b
			public const int workmail_layout = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int workmail_send = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int workmail_val = 2131034140;
			
			// aapt resource value: 0x7f050017
			public const int workphone_call = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int workphone_chat = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int workphone_layout = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int workphone_val = 2131034134;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DetailScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeScreen = 2130903042;
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
